# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b7cd6be34f2c499018ddc83f4e1821d06dc45c2af06e3dd991d0f184407a750d63c33c2b2c84c556a8f6593a9a1e246b288d357e381b240ae1a50d11987a2f4

test:
  secret_key_base: 475c286754b45547141fb5bcfae2affe0708155aa8b077de6c9d99bb0f163deda0a2ca96fe43fffa0db1080b63efa4feadb135b8e10815f3c81b268eaea5bbe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
