# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c3869b37006ccb6b0cbc7aea4374878902bae5066d3d27a49db99c59c7d488c1e9a54fd07dfa9cc41878dd97b81a0c5a083044afa8653773a0a77604371f640

test:
  secret_key_base: 9b86361957e8956fc9869d3608bb3f546a0166d7c46de9882d2035161db6e686a8502b7b1b26f9b50e7de79be0bf7e89756558b7ef7e6c35a7570f37c329e370

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
