# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c776a39b78cff4abee7c22bba14c722cc95381c96851e0cc0c43bc858bf49db476da758b5643ed7406025955ff597a3d82c956f7caf02e968a58d84daeff4ffb

test:
  secret_key_base: b14350dafa898df253bdec6de5792a1832662c5316c2387698210507641a778e0a40c9805d0b90c5d18a7fb0d33954b4e829fcf5e91110d4e5880604667d1b82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
