# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da17aa4780056d4399da5acb8fd4f8adb00b4df52a06857dc6c1d7a60928d4f55a0c51ffecc7d2d9cf0e9e39475e1d0e90fd53dbcf1f5045d271dca589084f0f

test:
  secret_key_base: 9e1529fc3502abbaca5ca3d7ae7fb1bf9399e1d0fcd1866d88e74119f6ea36a1761d2366a344c378e2945077a53cdbc06cc69301cc0df7f9c4627e1e73ff4768

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
