# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 693810f55565ae330662806d02f9b5f2787e574e89387f03229d88a38ded93258fc18027e7327b2a5275b9068deb2bd78e7232f9d3ea7efb01b672d1dfa0e353

test:
  secret_key_base: 40956b08b8b2fda43973992da01ce54df10d9f73e3865eb3f273c36bec744b47395b4d7817854f968941f767537fc87bd20a2386715aa3df5bef676d7c00193d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
