# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10b3b1e35d690e93fd8d7c65f222bb84c02e289bdb6bc120d58e672c2741f48046b2b3184cd4d55812905676385c32562483490856529e2cd87b9ff319c52ed5

test:
  secret_key_base: 896b69429fbf7a79a8d4f4fa54cd7a0e919c61b445a1336073f60fc57b65a38a8730f0cb32da6e4bbd01273c81338d28663bc28443b3227253efb0afdf2a11ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
